nome = input("Digite seu Nome:")
altura = input("Digite sua altura (m):")
peso = input("Agora seu peso (kg):")
imc = (float(peso)/float(altura)**2)
print("Olá, " + nome + " você tem " + altura + " de altura e pesa " + peso + " quilos e seu imc é: " +  "\n" + str(imc))
